BEGIN;

CREATE TABLE tarjeta (
    identificador VARCHAR(15) PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    nombre VARCHAR(50) NOT NULL UNIQUE,
    host VARCHAR(45) NOT NULL,
    script_de_autorizacion VARCHAR(255) NOT NULL,
    formato VARCHAR(4) NOT NULL DEFAULT 'JSON'
        CHECK (formato IN ('JSON', 'XML'))
);

CREATE TABLE courier (
    identificador VARCHAR(15) PRIMARY KEY,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    host VARCHAR(45) NOT NULL,
    script_de_consulta VARCHAR(255) NOT NULL,
    script_de_envio VARCHAR(255) NOT NULL,
    script_de_status VARCHAR(255) NOT NULL,
    formato VARCHAR(4) NOT NULL DEFAULT 'JSON'
        CHECK (formato IN ('JSON', 'XML'))
);

CREATE TABLE usuario (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hash_contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('ADMINISTRADOR', 'CLIENTE')),
    direccion VARCHAR(300) NOT NULL,
    codigo_de_destino CHAR(5) NOT NULL,
    telefono VARCHAR(25) NOT NULL,
    creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    nombre VARCHAR(150) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE categoria (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE producto (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INT NOT NULL REFERENCES categoria(id),
    url_img VARCHAR(500),
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    nombre VARCHAR(150) NOT NULL,
    descripcion VARCHAR(1000),
    precio DECIMAL(10,2) NOT NULL CHECK (precio >= 0)
);

CREATE TABLE variante_producto (
    id_variante INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INT NOT NULL REFERENCES producto(id),
    talla VARCHAR(20) NOT NULL,
    activo BOOLEAN NOT NULL DEFAULT TRUE,
    sku VARCHAR(50) NOT NULL UNIQUE,
    stock INT NOT NULL DEFAULT 0 CHECK (stock >= 0),
    stock_minimo INT NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    color VARCHAR(50) NOT NULL,
    CONSTRAINT unico_variante_producto_combinacion UNIQUE (id_producto, talla, color)
);

CREATE TABLE carrito (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL REFERENCES usuario(id),
    creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE articulo_en_carrito (
    id_item INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrito INT NOT NULL REFERENCES carrito(id) ON DELETE CASCADE,
    id_variante INT NOT NULL REFERENCES variante_producto(id_variante),
    cantidad INT NOT NULL CHECK (cantidad > 0),
    CONSTRAINT unico_articulo_carrito_variante UNIQUE (id_carrito, id_variante)
);

CREATE TABLE orden (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT NOT NULL REFERENCES usuario(id),
    id_tarjeta VARCHAR(15) NOT NULL REFERENCES tarjeta(identificador),
    id_courier VARCHAR(15) NOT NULL REFERENCES courier(identificador),
    creado_en TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    fecha_hora TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    subtotal_antes_de_envio DECIMAL(10,2) NOT NULL CHECK (subtotal_antes_de_envio >= 0),
    costo_envio DECIMAL(10,2) NOT NULL CHECK (costo_envio >= 0),
    total DECIMAL(10,2) NOT NULL,
    codigo_del_destino CHAR(5) NOT NULL,
    direccion_de_envio VARCHAR(300) NOT NULL,
    estado_de_pagado VARCHAR(10) NOT NULL CHECK (estado_de_pagado IN ('APROBADO', 'DENEGADO')),
    num_autorizacion VARCHAR(100) NOT NULL,
    num_envio VARCHAR(100) NOT NULL,
    estado_envio SMALLINT NOT NULL DEFAULT 1 CHECK (estado_envio BETWEEN 1 AND 5),
    CONSTRAINT total_orden_correcto CHECK (total = subtotal_antes_de_envio + costo_envio)
);

CREATE TABLE detalle_orden (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden BIGINT NOT NULL REFERENCES orden(id) ON DELETE CASCADE,
    id_variante INT NOT NULL REFERENCES variante_producto(id_variante),
    precio_por_unidad DECIMAL(10,2) NOT NULL CHECK (precio_por_unidad >= 0),
    cantidad_de_articulos INT NOT NULL CHECK (cantidad_de_articulos > 0),
    CONSTRAINT unico_detalle_orden_variante UNIQUE (id_orden, id_variante)
);

CREATE INDEX indice_producto_categoria ON producto(id_categoria);
CREATE INDEX indice_variante_producto ON variante_producto(id_producto);
CREATE INDEX indice_carrito_usuario ON carrito(id_usuario);
CREATE INDEX indice_orden_usuario ON orden(id_usuario);

COMMIT;
